export interface BookData {
  title: string;
  author: string;
  isbn?: string;
}

export const books: BookData[] = [
  // === English: Fiction & Philosophy ===
  { title: "The Brothers Karamazov", author: "Fyodor Dostoyevsky", isbn: "9780140449242" },
  { title: "Notes from Underground", author: "Fyodor Dostoyevsky", isbn: "9780679734529" },
  { title: "White Nights", author: "Fyodor Dostoyevsky", isbn: "9780140446388" },
  { title: "The Stranger", author: "Albert Camus", isbn: "9780679720201" },
  { title: "The Metamorphosis", author: "Franz Kafka", isbn: "9780553213690" },
  { title: "A Hunger Artist", author: "Franz Kafka" },
  { title: "Letters to Milena", author: "Franz Kafka", isbn: "9780805211932" },
  { title: "The Kite Runner", author: "Khaled Hosseini", isbn: "9781594480003" },
  { title: "A Thousand Splendid Suns", author: "Khaled Hosseini", isbn: "9781594631931" },
  { title: "And the Mountains Echoed", author: "Khaled Hosseini", isbn: "9781594632389" },
  { title: "The Alchemist", author: "Paulo Coelho", isbn: "9780062315007" },
  { title: "Animal Farm", author: "George Orwell", isbn: "9780451526342" },
  { title: "The Fault in Our Stars", author: "John Green", isbn: "9780525478812" },
  { title: "Mr. Chips", author: "James Hilton", isbn: "9780340836436" },
  { title: "The Bastard of Istanbul", author: "Elif Shafak", isbn: "9780143114835" },
  { title: "Forty Rules of Love", author: "Elif Shafak", isbn: "9780670021458" },
  { title: "My Name Is Red", author: "Orhan Pamuk", isbn: "9780375706851" },

  // === English: Non-Fiction ===
  { title: "Man's Search for Meaning", author: "Viktor E. Frankl", isbn: "9780807014295" },
  { title: "Atomic Habits", author: "James Clear", isbn: "9780735211292" },
  { title: "Think and Grow Rich", author: "Napoleon Hill", isbn: "9781585424337" },
  { title: "The 48 Laws of Power", author: "Robert Greene", isbn: "9780140280197" },
  { title: "The Subtle Art of Not Giving a F*ck", author: "Mark Manson", isbn: "9780062457714" },
  { title: "The Power of Positive Thinking", author: "Norman Vincent Peale", isbn: "9780743234806" },
  { title: "The Five Love Languages", author: "Gary Chapman", isbn: "9780802412706" },
  { title: "The Great Philosophers", author: "Stephen Law", isbn: "9781847971735" },
  { title: "The Psychology Book: Big Ideas Simply Explained", author: "DK", isbn: "9780756689704" },
  { title: "Reclaim Your Heart", author: "Yasmin Mogahed", isbn: "9781508476482" },
  { title: "The Naked Woman", author: "Desmond Morris", isbn: "9780312380885" },
  { title: "Me & Rumi: The Autobiography of Shams-i Tabrizi", author: "William C. Chittick (trans.)", isbn: "9781887751943" },
  { title: "The Way of Passion: A Celebration of Rumi", author: "Andrew Harvey", isbn: "9781585424818" },
  { title: "Fragrance of Sufism", author: "M. Mahmood Ali Qutab" },

  // === English: Current Affairs & History ===
  { title: "The Afghanistan Papers", author: "Craig Whitlock", isbn: "9781982159009" },
  { title: "In the Hands of the Taliban", author: "Yvonne Ridley", isbn: "1861054955" },
  { title: "The Sewing Circles of Herat", author: "Christina Lamb", isbn: "9780060505276" },
  { title: "The War of Ideology", author: "Sami-ul-Haq" },
  { title: "After the Prophet", author: "Lesley Hazleton", isbn: "9780385523943" },
  { title: "The Crisis of Islam", author: "Bernard Lewis", isbn: "9780812967852" },
  { title: "Living Islam", author: "Akbar S. Ahmed", isbn: "9781850439200" },
  { title: "The Way of Prophet Muhammad", author: "Sheikh M.S." },
  { title: "Muslim Heroes", author: "Dr. M. Esmail" },
  { title: "Why Islam is My Only Choice", author: "M. Haneef Shahid" },
  { title: "The Rightly Guided", author: "Shakil" },
  { title: "United States of Islam", author: "Jawed ul Haq Siddiqui" },
  { title: "The Islamic Guidelines", author: "Muhammad bin Jamil Zino" },

  // === Urdu: Islamic Scholarship & Sufism ===
  { title: "Kulyat-e-Iqbal", author: "Allama Muhammad Iqbal" },
  { title: "Khutbaat", author: "Dr. Zakir Naik" },
  { title: "Hikayat-e-Sahaba", author: "Maulana Muhammad Zakaria Kandhalvi" },
  { title: "Riyad-us-Saliheen", author: "S.M. Madni Abbasi" },
  { title: "Taqwiyat-ul-Iman", author: "Shah Ismail Shaheed" },
  { title: "Hujjat-ullah-ul-Baligha", author: "Ubaid Ullah Sindhi" },
  { title: "Seerat-e-Rasool", author: "Allama Suleman Nadvi" },
  { title: "Seerat-e-Rasool", author: "Prof. Noor Bakhsh" },
  { title: "Hazrat Muhammad (PBUH) Paighambar-e-Islam", author: "Muhammad Asim Butt" },
  { title: "Hazrat Muawiya Aur Tareekhi Haqaiq", author: "Mufti Muhammad Taqi Usmani" },
  { title: "Seerat-e-Amir Muawiya", author: "Kashif Ahmed" },
  { title: "Islam Aur Maghrib Ka Tasaddum", author: "Asrar-ul-Haq" },
  { title: "Islam Aur Siyasi Nazariyat", author: "Mufti Muhammad Taqi Usmani" },
  { title: "Zikr-o-Fikr", author: "Mufti Muhammad Taqi Usmani" },
  { title: "Jahan-e-Deeda", author: "Mufti Muhammad Taqi Usmani" },
  { title: "Tufaan Se Sahil Tak", author: "Muhammad Asad" },
  { title: "Zad-e-Rah", author: "Maulana Jaleel Ahsan" },
  { title: "Gunnah Ki Taseer", author: "Maulana Hidayat Ullah" },
  { title: "Khud Se Khuda Tak", author: "Muhammad Nasir Iftikhar" },
  { title: "Maulana Rumi — Hayat o Afkaar", author: "Dr. Afzal Iqbal" },
  { title: "Hikayat-e-Rumi", author: "Maulana Jalaluddin Rumi" },
  { title: "Suno Tum Sitare Ho", author: "Ali Shirazi" },
  { title: "Yani", author: "Jaun Elia" },
  { title: "Tareekh-e-Islam", author: "Kalim Ullah" },
  { title: "Pashtun Tareekh Kay Aainay Mein", author: "Syed Bahadur Shah" },
  { title: "Huzoor Ka Bachpan", author: "Shahbaz Kausar" },
  { title: "Quran Aasan", author: "Dr. Malik Ghulam" },

  // === Pashto ===
  { title: "So Panni Nasha (شعر)", author: "Waman Niyazi" },
  { title: "Da Bazgar Lor (کيسې)", author: "Noor Muhammad Tarakai" },
];
